### ISSUE TITLE
ReferenceError: value is not defined

### ISSUE THREAD

**Issue by MeteorVE** [MonoLogueChi/hexo-tag-mmedia#5]
我的環境 : 
Hexo 4.2.1 + Next 7.8.0

報錯訊息 :
```
ReferenceError: value is not defined
    at C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo-tag-mmedia\util\tag\aplayer.js:37:74
    at Array.forEach (<anonymous>)
    at AplayerTag.parse (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo-tag-mmedia\util\tag\aplayer.js:18:22)
    at new AplayerTag (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo-tag-mmedia\util\tag\aplayer.js:11:30)
    at Object.<anonymous> (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo-tag-mmedia\index.js:25:19)
    at NunjucksTag._run (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo\lib\extend\tag.js:170:18)
    at NunjucksTag.run (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo\lib\extend\tag.js:166:15)
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:23:67)
    at Template.render (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\nunjucks\src\environment.js:550:10)
    at Environment.renderString (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\nunjucks\src\environment.js:378:17)
    at C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo\lib\extend\tag.js:120:48
    at tryCatcher (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\bluebird\js\release\promise.js:209:30)
    at Tag.render (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo\lib\extend\tag.js:120:18)
    at Object.onRenderEnd (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo\lib\hexo\post.js:291:22)
    at C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\hexo\lib\hexo\render.js:79:21
    at tryCatcher (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\MeteorV\Desktop\新增資料夾\blog\node_modules\bluebird\js\release\async.js:93:12)
```

升級 Next 和 Hexo 之後進入了折騰階段
為了確保乾淨，直接開新資料夾建一個新的 blog 環境
裝完此插件後
直接編譯就會產生以上 error

不過神奇的是，好像還是可以正常顯示。
但每次 generate 都會看到 error 心裡會毛毛的 ... 
還沒測試過 aplayer 以外的 Tag 會不會出錯

**Comment by MonoLogueChi** [comment]
方便看一下你的 _config.yml 裡 mmedia 的配置嗎

**Comment by MeteorVE** [comment]
找到問題了，我以前用 hexo-tag-aplayer 有這麼一段

```
{% aplayerlrc  "大丈夫" "RADWIMPS" "xxx.mp3" "https://i.imgur.com/MRojphb.png"  "width:70%" "loop:one"  %}

[00:00.00]製作 by MeteorV (下略)
{% endaplayerlrc %}

```

但是會特別在這邊報錯，應該是格式還是哪邊出錯吧
(如果是不認識 Tag，會丟 hexo Nunjucks Error)

**Comment by MonoLogueChi** [comment]
lrc目前的模式问题比较打，暂时不推荐使用，以后会完全重写这一部分
